### PR TITLE
Add logo svg files

### PR DESCRIPTION
**Pull request by sprngr**
This PR adds in the current concept logo for Fontship addressing open issue #31.

The files included in SVG format are two open and filled variants, one with a logo and text, and a source vector. The text used is done in [Fanwood](https://github.com/theleagueof/fanwood) to align with branding used on the League of Movable Type website. The font used in the vectors has been rendered as curves to maintain the font in all files except `fontship_truck_source`.

*Demo*:

fontship_demo

### CODE REVIEW

**Comment by alerque** [comment]
Thanks! I think this is a very workable place to start. I'll mess around with how well they actually fit into where it needs to go.

Before I can merge this though I have to ask ... the project as posted right now is licensed AGPL. There is a good chance than I'll kind of be bullied into changing this to be GPL before font projects that want to be published on Google Fonts can use this without making a scene (see #35). Since tracking down contributors after the fact to approve a license change is a hassle, can I just ask up front if you'll be willing to have your contributions re-licensed as GPL-3 were I to make the decision to do so?

**Comment by sprngr** [comment]
@alerque Yes, I am willing to have contributions relicensed under GPL-3

**Comment by alerque** [comment]
I just had a poke at this. What do you think of the two changes I just pushed (skew + front bumper)?

icon-source

**Comment by alerque** [comment]
As long as I was fooling around, I also thought we could re-use Fanwood as an air-horn. :man_shrugging: 

icon-source-joke

**Comment by alerque** [comment]
On a more serious note, I think what we're going to want for the favicon size is just a solid truck. For example here is a badge from the current black truck with F:

![shields badge demo](https://img.shields.io/github/workflow/status/theleagueof/raleway/Fontship?label=fontship&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAxNDIgMTA3IiB4bWw6c3BhY2U9InByZXNlcnZlIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTIxNS4yOSAtNDY1LjgyKSI+CiAgICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTkzLjM0IDEuMjE5OCkiPgogICAgICAgICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCg2LjE4NTggMCAwIDYuMTg1OCAxOC4yNjcgNDQ4LjU1KSI+CiAgICAgICAgICAgICAgICA8cmVjdCB4PSIxIiB5PSIzIiB3aWR0aD0iMTUiIGhlaWdodD0iMTMiIHN0cm9rZT0iIzAwMCIgc3Ryb2tlLXdpZHRoPSIuODFweCIvPgogICAgICAgICAgICA8L2c+CiAgICAgICAgCiAgICAgICAgCiAgICAgICAgICAgIDxnIHRyYW5zZm9ybT0ibWF0cml4KC45OTM2NCAwIDAgLjk5MzY0IC0yMDcuMDggMzk4Ljg0KSI+CiAgICAgICAgICAgICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCg4MC41MzkgMCAwIDgwLjUzOSAyNTcuOTIgMTM2LjgzKSI+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0ibTAuMDE3LTAuMDE1YzAgMC4wMTcgMWUtMyAwLjAyMSAwLjAxNSAwLjAyMSAwLjAyMyAwIDAuMDc1LTNlLTMgMC4xMDUtM2UtM3MwLjA3OSAzZS0zIDAuMTAyIDNlLTNjMC4wMTIgMCAwLjAxMi01ZS0zIDAuMDEyLTAuMDIgMC0wLjAxMiAwLTAuMDE2LTAuMDEyLTAuMDE2aC0wLjA2N2MtNWUtMyAwLTZlLTMgLTJlLTMgLTVlLTMgLTZlLTMgNWUtMyAtMC4wNDQgMC4wMzYtMC4yNjIgMC4wMzktMC4yNzggMmUtMyAtOGUtMyAyZS0zIC04ZS0zIDAuMDE3LThlLTNoMC4xNDNjMC4wNDMgMCAwLjA0NyA0ZS0zIDAuMDQ3IDAuMDExIDAgM2UtMyAtN2UtMyAwLjA0NS05ZS0zIDAuMDU4LTFlLTMgMC4wMSAwLjAxMiAwLjAxIDAuMDIgMC4wMSA3ZS0zIDAgMC4wMTUtMmUtMyAwLjAxNi05ZS0zIDJlLTMgLTAuMDEzIDZlLTMgLTAuMDQ3IDAuMDEyLTAuMDc5IDdlLTMgLTAuMDM4IDAuMDE0LTAuMDY4IDAuMDE0LTAuMDc4IDAtOGUtMyAtMC4wMS05ZS0zIC0wLjAxNi05ZS0zIC03ZS0zIDAtMC4wMTggMC0wLjAxOSA5ZS0zbC04ZS0zIDAuMDQzYy0yZS0zIDllLTMgLTAuMDI0IDAuMDExLTAuMDQ0IDAuMDExaC0wLjE1NmMtMC4wMTMgMC0wLjAxMiAwLTAuMDEyLTRlLTMgMC0yZS0zIDAtNWUtMyAxZS0zIC05ZS0zIDVlLTMgLTAuMDM1IDAuMDMzLTAuMjQzIDAuMDQtMC4yNjcgMC4xIDAgMC4yMTQgM2UtMyAwLjIzMiA2ZS0zIC0xZS0zIDAuMDEyLTVlLTMgMC4wNjYtNWUtMyAwLjA3MSAwIDAuMDExLTFlLTMgMC4wMTcgMC4wMTcgMC4wMTcgMC4wMTYgMCAwLjAxOS0zZS0zIDAuMDE5LTAuMDEzIDJlLTMgLTAuMDY5IDllLTMgLTAuMTE3IDllLTMgLTAuMTI1IDAtMC4wMTQtNGUtMyAtMC4wMTQtMC4wMi0wLjAxNC05ZS0zIDAtMC4wMTQgMWUtMyAtMC4wMTYgMC4wMTUtMWUtMyA5ZS0zIDJlLTMgMC4wMS0wLjA2NiAwLjAxLTAuMDQzIDAtMC4xNTYgM2UtMyAtMC4yMDkgM2UtMyAtMC4wMzUgMC0wLjEwNy0zZS0zIC0wLjExNC0zZS0zIC05ZS0zIDAtMC4wMTUgNGUtMyAtMC4wMTUgMC4wMTcgMCAwLjAxNyAwLjAxIDAuMDE4IDAuMDIyIDAuMDE4aDAuMDU0czFlLTMgM2UtMyAxZS0zIDdlLTNjMCAwLjA3Ni0wLjA3NyAwLjU1Ni0wLjA4MyAwLjU5NmgtMC4wNDJjLTAuMDE2IDAtMC4wMTkgMWUtMyAtMC4wMTkgMC4wMTV6IiBmaWxsPSIjZmZmIiBmaWxsLXJ1bGU9Im5vbnplcm8iLz4KICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgPC9nPgogICAgICAgIAogICAgICAgIAogICAgICAgICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCg2LjE4NTggMCAwIDYuMTg1OCAxOC4yNjcgNDQ4LjU1KSI+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJtMTYgOGg0bDAuNjMzIDAuNjMzYzEuNTE1IDEuNTE1IDIuMzY3IDMuNTcxIDIuMzY3IDUuNzE1djEuNjUyaC03di04eiIgZmlsbC1ydWxlPSJub256ZXJvIiBzdHJva2U9IiMwMDAiIHN0cm9rZS13aWR0aD0iLjgxcHgiLz4KICAgICAgICAgICAgPC9nPgogICAgICAgIAogICAgICAgIAogICAgICAgICAgICA8ZyB0cmFuc2Zvcm09Im1hdHJpeCgzLjg4MjEgMCAwIDMuODgyMSAtMzgzLjEzIDM5Mi4wOSkiPgogICAgICAgICAgICAgICAgPHJlY3QgeD0iMTMwLjMyIiB5PSIyOS4wOTYiIHdpZHRoPSI1LjQzNiIgaGVpZ2h0PSI0LjE1NyIvPgogICAgICAgICAgICA8L2c+CiAgICAgICAgCiAgICAgICAgCiAgICAgICAgICAgIDxnIHRyYW5zZm9ybT0ibWF0cml4KDYuMTg1OCAwIDAgNi4xODU4IDE4LjI2NyA0MzguNDUpIj4KICAgICAgICAgICAgICAgIDxjaXJjbGUgY3g9IjUuNSIgY3k9IjE4LjUiIHI9IjIuNSIgc3Ryb2tlPSIjMDAwIiBzdHJva2Utd2lkdGg9Ii44MXB4Ii8+CiAgICAgICAgICAgIDwvZz4KICAgICAgICAKICAgICAgICAKICAgICAgICAgICAgPGcgdHJhbnNmb3JtPSJtYXRyaXgoNi4xODU4IDAgMCA2LjE4NTggMTguOTAzIDQzOC40NSkiPgogICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMTguNSIgY3k9IjE4LjUiIHI9IjIuNSIgc3Ryb2tlPSIjMDAwIiBzdHJva2Utd2lkdGg9Ii44MXB4Ii8+CiAgICAgICAgICAgIDwvZz4KICAgICAgICA8L2c+CiAgICA8L2c+Cjwvc3ZnPgo=)

**Comment by sprngr** [comment]
> I just had a poke at this. What do you think of the two changes I just pushed (skew + front bumper)?
I love this. This minor change makes it feel more active and the front bumper is 👌 

> As long as I was fooling around, I also thought we could re-use Fanwood as an air-horn. 🤷‍♂️
May want to shrink the F a bit for the airhorn. lol

> On a more serious note, I think what we're going to want for the favicon size is just a solid truck.

I agree, the solid one works a lot better given text becomes unreadable at that size.

**Comment by alerque** [comment]
I made a few minor touchups, then redid the files such that there is a single source file than needs editing for any changes to the logo and build targets that generate the others. Since the dependencies for this are a bit Linux desktop oriented (although not exclusive) and the generated SVGs are tiny enough I've committed them as well. I kind of have to because Fontship is built and released almost entirely automatically in CI. I don't really feel like adding `inkscape`, `scour` and `svgo` to the dependency chain, especially as Inkscape needs to run with a GUI to run these.

Long term I think it would be fun to redraw the logo from scratch using [`drawbot-skia`](https://github.com/justvanrossum/drawbot-skia) — something that I expect will eventually make its way to being a dependency of Fontship itself (for specimens!) so it will make a lot more sense to build using that than Inkscape.

**Pull request merged**
